#!/bin/bash

# variables
declare gitHubUsername=MauricioBalderrama
declare gitHubRepositoryName=macOS-Hacks

# settings
declare setupSubFolder=core
declare cloneFolder=~/${gitHubRepositoryName}
declare repositoryName="${gitHubRepositoryName//[-]/ }"  