#!/bin/bash

# libs
. config

# download repository
if [[ ! -d ${cloneFolder} ]]; then
    # clone
    echo ""
    echo "Downloading ${repositoryName}..."
    git clone git@github.com:${gitHubUsername}/${gitHubRepositoryName}.git ${cloneFolder}
else
    # update
    echo ""
    echo "Updating ${repositoryName}..."
    cd $cloneFolder
    git pull origin master
fi

# setup
cd ${cloneFolder}/${setupSubFolder}
source setup
