#!/bin/bash

# variables
declare gitHubUsername=MauricioBalderrama
declare gitHubRepositoryName=macOS-Hacks
declare setupSubFolder=

# settings
declare cloneFolder=~/${gitHubRepositoryName}
declare repositoryName="${gitHubRepositoryName//[-]/ }"  

# download repository
if [[ ! -d ${cloneFolder} ]]; then
    # clone
    echo ""
    echo "Downloading ${repositoryName}..."
    git clone git@github.com:${gitHubUsername}/${gitHubRepositoryName}.git ${cloneFolder}
else
    # update
    echo ""
    echo "Updating ${repositoryName}..."
    cd $cloneFolder
    git pull origin master
fi

# update remote to use SSH
cd ${cloneFolder}
git remote rm origin
git remote add origin git@github.com:${gitHubUsername}/${gitHubRepositoryName}

# run
cd ${cloneFolder}${setupSubFolder}
source setup
