#!/bin/bash

# Start message
echo "${repositoryName} starting..."

# Close any open System Preferences panes
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Configure: system
source . core/system.sh

# Configure: io
source . core/io.sh

# Configure: coreApps
source . core/apps.sh

# Finish message
echo "${repositoryName} completed."
echo "Some changes require a logout/restart to take effect."
