#!/bin/bash

##########
# Mojave #
##########

# Magic Mouse: Swipe Between Pages: scroll left or right with one finger
# TODO: If I will be using Safari... probalby not...

# Magic Mouse: Swipe Between Pages: scroll left or right with one finger (for Google Chrome)
defaults write com.google.Chrome AppleEnableMouseSwipeNavigateWithScrolls -bool true  

# Magic Mouse: Smart Zoom: enable double-tap with one finger
# TODO

# Magic Mouse: Tracking Speed: faster (default0.6875)
defaults write NSGlobalDomain com.apple.mouse.scaling 1

# Magic Mouse: enable right-click
defaults write com.apple.driver.AppleBluetoothMultitouch.mouse MouseButtonMode TwoButton

# Trackpad: Enable Dragging: three finger drag
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool true
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool true

# Keyboard: faster keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10

###############
# High Sierra #
###############

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Use scroll gesture with the Ctrl (^) modifier key to zoom
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144
# Follow the keyboard focus while zoomed in
defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

# Disable natural scrolling
#defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

# Disable press-and-hold for keys in favor of key repeat 
# (not good if you require special chars [non-english])
#defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

#########
# Untested
#########

# # Increase sound quality for Bluetooth headphones/headsets
# defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

# # Trackpad: map bottom right corner to right-click
# # dont seem to work
# # defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
# # defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
# # defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
# # defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

# # Set language and text formats
# # Note: if you’re in the US, replace `EUR` with `USD`, `Centimeters` with
# # `Inches`, `en_GB` with `en_US`, and `true` with `false`.
# #defaults write NSGlobalDomain AppleLanguages -array "en" "nl"
# #defaults write NSGlobalDomain AppleLocale -string "en_GB@currency=EUR"
# #defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
# #defaults write NSGlobalDomain AppleMetricUnits -bool true

# # Enable subpixel font rendering on non-Apple LCDs
# # Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
# defaults write NSGlobalDomain AppleFontSmoothing -int 1

# # Enable HiDPI display modes (requires restart)
# sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

# # Auto-play videos when opened with QuickTime Player
# defaults write com.apple.QuickTimePlayerX MGPlayMovieOnOpen -bool true