#!/bin/bash

# Start message
echo "Starting."

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Close any open System Preferences panes
osascript -e 'tell application "System Preferences" to quit'

# Configure: io
source io

# Configure: apps
source apps

# Finish message
echo "Completed."
echo ""
echo "Some changes require a logout/restart to take effect."
