#!/bin/bash

# Set standby delay to 24 hours (default is 1 hour)
sudo pmset -a standbydelay 86400

# Set standby delay to 24 hours (default is 1 hour: 10800)
# standbydelay specifies the delay, in seconds, before writing the hibernation 
# image to disk and powering off memory for Standby.
sudo pmset -a standbydelay 86400

# Set stand by to 0 (default is 1)
# standby causes kernel power management to automatically hibernate a
# machine after it has slept for a specified time period. This saves power
# while asleep. This setting defaults to ON for supported hardware. The
# setting standby will be visible in pmset -g if the feature is supported
# on this machine.
sudo pmset -a standby 0

# disksleep - disk spindown timer; replaces 'spindown' argument in 10.4
# (value in minutes, or 0 to disable)
sudo pmset -a disksleep 0

#sleep - system sleep timer (value in minutes, or 0 to disable)
sudo pmset -a sleep 0

# autopoweroff is enabled by default on supported platforms as an implemen-
# tation of Lot 6 to the European Energy-related Products Directive. After
# sleeping for <autopoweroffdelay> seconds, the system will write a hiber-
# nation image and go into a lower power chipset sleep. Wakeups from this
# state will take longer than wakeups from regular sleep.
sudo pmset -a autopoweroff 0

# displaysleep - display sleep timer; replaces 'dim' argument in 10.4
# (value in minutes, or 0 to disable)
sudo pmset -c displaysleep 10
sudo pmset -b displaysleep 5

# Remove the sleep image file to save disk space
# Disabled for now. Not compatible with High Sierra: https://github.com/mathiasbynens/dotfiles/issues/811
# System Integrity Protection
# sudo rm /private/var/vm/sleepimage
# Create a zero-byte file instead…
# sudo touch /private/var/vm/sleepimage
# …and make sure it can’t be rewritten
# sudo chflags uchg /private/var/vm/sleepimage

# hibernatemode - change hibernation mode. Please use caution. (value =
# integer)
sudo pmset -a hibernatemode 0

#  For example, on desktops that support standby a hibernation image will be
#  written after the specified standbydelay time. To disable hibernation
#  images completely, ensure hibernatemode standby and autopoweroff are all
#  set to 0.
# SAFE SLEEP ARGUMENTS
#      hibernatemode supports values of 0, 3, or 25. Whether or not a hiberna-
#      tion image gets written is also dependent on the values of standby and
#      autopoweroff

#      For example, on desktops that support standby a hibernation image will be
#      written after the specified standbydelay time. To disable hibernation
#      images completely, ensure hibernatemode standby and autopoweroff are all
#      set to 0.

#      hibernatemode = 0 by default on desktops. The system will not back memory
#      up to persistent storage. The system must wake from the contents of mem-
#      ory; the system will lose context on power loss. This is, historically,
#      plain old sleep.

#      hibernatemode = 3 by default on portables. The system will store a copy
#      of memory to persistent storage (the disk), and will power memory during
#      sleep. The system will wake from memory, unless a power loss forces it to
#      restore from hibernate image.

#      hibernatemode = 25 is only settable via pmset. The system will store a
#      copy of memory to persistent storage (the disk), and will remove power to
#      memory. The system will restore from disk image. If you want "hiberna-
#      tion" - slower sleeps, slower wakes, and better battery life, you should
#      use this setting.

#      Please note that hibernatefile may only point to a file located on the
#      root volume.

# Never go into computer sleep mode
sudo systemsetup -setcomputersleep Off > /dev/null

# Set the timezone; see `sudo systemsetup -listtimezones` for other values
sudo systemsetup -settimezone "America/La_Paz" > /dev/null

# Restart automatically if the computer freezes
sudo systemsetup -setrestartfreeze on

# Disable the sound effects on boot. 
# TODO: Does not work on restart.
source noBootSound/install.sh

# Set sidebar icon size to medium
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

# Always show scrollbars. Values: `WhenScrolling`, `Automatic` and `Always`
defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Expand print panel by default
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Disable the “Are you sure you want to open this application?” dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Disable automatic termination of inactive apps
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

# Reveal IP address, hostname, OS version, etc. when clicking the clock in the login window
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Disable Notification Center and remove the menu bar icon
#launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null
# Note: Operation not permitted while System Integrity Protection is engaged
# TODO: New solution

#########
# Untested
#########

# # Disable automatic capitalization
# defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# # Disable smart dashes
# defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# # Disable automatic period substitution
# defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# # Disable smart quotes
# defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# # Disable auto-correct
# defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# # Stop iTunes from responding to the keyboard media keys
# launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null

# # Require password immediately after sleep or screen saver begins
# defaults write com.apple.screensaver askForPassword -int 1
# defaults write com.apple.screensaver askForPasswordDelay -int 0

# # Set Help Viewer windows to non-floating mode
# defaults write com.apple.helpviewer DevMode -bool true

# # Disable the over-the-top focus ring animation
# defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

# # Increase window resize speed for Cocoa applications
# defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

# # Save to disk (not to iCloud) by default
# defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# # Remove duplicates in the “Open With” menu (also see `lscleanup` alias)
# /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

# # Display ASCII control characters using caret notation in standard text views
# # Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`
# defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true

# # Set computer name (as done via System Preferences → Sharing)
# #sudo scutil --set ComputerName "0x6D746873"
# #sudo scutil --set HostName "0x6D746873"
# #sudo scutil --set LocalHostName "0x6D746873"
# #sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "0x6D746873"

# # Disable Resume system-wide
# #defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

# # Disable the crash reporter
# #defaults write com.apple.CrashReporter DialogType -string "none"

# # Fix for the ancient UTF-8 bug in QuickLook (https://mths.be/bbo)
# # Commented out, as this is known to cause problems in various Adobe apps :(
# # See https://github.com/mathiasbynens/dotfiles/issues/237
# #echo "0x08000100:0" > ~/.CFUserTextEncoding

# # Set a custom wallpaper image. `DefaultDesktop.jpg` is already a symlink, and
# # all wallpapers are in `/Library/Desktop Pictures/`. The default is `Wave.jpg`.
# #rm -rf ~/Library/Application Support/Dock/desktoppicture.db
# #sudo rm -rf /System/Library/CoreServices/DefaultDesktop.jpg
# #sudo ln -s /path/to/your/image /System/Library/CoreServices/DefaultDesktop.jpg